#!/bin/zsh

touch zsh/zprofile.local
ln -s "$(pwd)/zsh/zprofile.local" ~/.zprofile.local
ln -s "$(pwd)/zsh/zprofile" ~/.zprofile
ln -s "$(pwd)/zsh/zshrc" ~/.zshrc
ln -s "$(pwd)/zsh/zshenv" ~/.zshenv

ln -s "$(pwd)/.editorconfig" ~/.editorconfig

brew install git
ln -s "$(pwd)/git/gitignore.global" ~/.gitignore
ln -s "$(pwd)/git/gitconfig" ~/.gitconfig
[ ! -f git/gitconfig.local ] && cp git/gitconfig.local{.template,}
ln -s "$(pwd)/git/gitconfig.local" ~/.gitconfig.local

brew install gnupg pinentry-mac
ln -s "$(pwd)/gpg/gpg-agent-mac.conf" ~/.gnupg/gpg-agent.conf

brew install ripgrep fzf nodejs yarn

brew install vim
# brew tap maralla/pack
# brew install pack
ln -s "$(pwd)/vim" ~/.vim
# pack install

# brew install --HEAD tmux
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# ln -s "$(pwd)/tmux/tmux.conf" ~/.tmux.conf

# brew install --HEAD mosh

# conda config --set changeps1 False

mkdir -p ~/bin