#!/usr/bin/env zsh

mkdir -p ~/.config

if [[ `uname` == "Darwin" ]]; then
    brew install git gnupg pinentry-mac ripgrep fzf vim neovim zoxide hexyl jq direnv
fi

touch zsh/zprofile.local
ln -s "$(pwd)/zsh/zprofile.local" ~/.zprofile.local
ln -s "$(pwd)/zsh/zprofile" ~/.zprofile
ln -s "$(pwd)/zsh/zshrc" ~/.zshrc
ln -s "$(pwd)/zsh/zshenv" ~/.zshenv

ln -s "$(pwd)/.editorconfig" ~/.editorconfig

ln -s "$(pwd)/git/gitignore.global" ~/.gitignore
ln -s "$(pwd)/git/gitconfig" ~/.gitconfig
[ ! -f git/gitconfig.local ] && cp git/gitconfig.local{.template,}
ln -s "$(pwd)/git/gitconfig.local" ~/.gitconfig.local

if [[ `uname` == "Darwin" ]]; then
    ln -s "$(pwd)/gpg/gpg-agent-mac.conf" ~/.gnupg/gpg-agent.conf
fi

if [[ -n "$WSL_DISTRO_NAME" ]]; then
    ln -s "$(pwd)/gpg/gpg-agent-wsl.conf" ~/.gnupg/gpg-agent.conf
fi

# brew tap maralla/pack
# brew install pack
ln -s "$(pwd)/vim" ~/.vim
# pack install

ln -s "$(pwd)/nvim" ~/.config/nvim

brew install --HEAD tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
ln -s "$(pwd)/tmux/tmux.conf" ~/.tmux.conf

# brew install --HEAD mosh

# ln -s "$(pwd)/conda/condarc" ~/.condarc

ln -s "$(pwd)/starship/starship.toml" ~/.config/starship.toml

mkdir -p ~/bin

if [[ `uname` == "Darwin" ]]; then
    swiftc support/SystemThemeChecker.swift -o ~/bin/SystemThemeChecker -O
fi

if [[ `uname` == "Darwin" ]]; then
    /usr/bin/tic -x support/tmux-256color.src
fi
