" ------------------------------------------------------------------------------
"  Vim configuration. Theoretically requires Vim 7.4+ but tested on 8.0 only.
" ------------------------------------------------------------------------------

" Vim is not vi
set nocompatible

" ------------------------------------------------------------------------------
"  PLUGINS
" ------------------------------------------------------------------------------

" First installation:
"   $ curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"   $ vim +PlugInstall

call plug#begin('~/.vim/plugged')

" Color schemes
Plug 'altercation/vim-colors-solarized'
Plug 'tomasr/molokai'

" Airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Syntax highlighting
Plug 'othree/html5.vim'
Plug 'plasticboy/vim-markdown'
Plug 'mxw/vim-jsx'
Plug 'leafgarland/typescript-vim'
Plug 'lervag/vimtex'
Plug 'jeaye/color_coded', {
  \   'do': 'cmake -DDOWNLOAD_CLANG=FALSE . && make && make install'
  \ }
Plug 'pangloss/vim-javascript'

" Tmux integration
Plug 'tmux-plugins/vim-tmux-focus-events'
Plug 'tmux-plugins/vim-tmux'
Plug 'benmills/vimux'
Plug 'christoomey/vim-tmux-navigator'

" Git integration
Plug 'tpope/vim-fugitive'
Plug 'gregsexton/gitv'
Plug 'airblade/vim-gitgutter'

" Autocompletion
Plug 'Valloric/YouCompleteMe', {
  \   'do': './install.py --clang-completer --system-libclang --tern-completer --gocode-completer'
  \ }
Plug 'rdnetto/YCM-Generator'

" Save keystrokes
Plug 'easymotion/vim-easymotion'
Plug 'Raimondi/delimitMate'
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'

" Substitutions improvement
Plug 'tpope/vim-abolish'

" Code comments
Plug 'scrooloose/nerdcommenter'

" Linters integration
Plug 'scrooloose/syntastic'

" File and buffer management
Plug 'scrooloose/nerdtree'
Plug 'wincent/Command-T', {
  \   'do': 'cd ruby/command-t && ruby extconf.rb && make'
  \ }
Plug 'danro/rename.vim'

" Undo tree
Plug 'sjl/gundo.vim'

" Improvements for Node.js
Plug 'moll/vim-node'

" ASCII drawing
Plug 'vim-scripts/DrawIt'

" LLDB debugger integration
Plug 'gilligan/vim-lldb'

" Maintain own working directories for tabs
Plug 'kana/vim-tabpagecd'

" Create and resize windows
Plug 'wellle/visual-split.vim'

" Search in project
Plug 'mileszs/ack.vim'

call plug#end()

" Enable Vim's matchit plugin
packadd! matchit

" ------------------------------------------------------------------------------
"  SETTINGS
" ------------------------------------------------------------------------------

" Enable filetype detection, plugins loading and automatic indentation
filetype plugin indent on

" Enable syntax highlighting and setup colorscheme
syntax on
colorscheme solarized
set background=dark
highlight Normal ctermbg=none
highlight NonText ctermbg=none

" Make status line informative
set ruler
set showmode
set showcmd

" Line numbers
set number
autocmd WinEnter,FocusGained * :setlocal number relativenumber
autocmd WinLeave,FocusLost   * :setlocal number norelativenumber

" Search settings
set incsearch
set hlsearch
set ignorecase
set smartcase
set gdefault

" Let files be opened over unsaved buffers
set hidden

" Restore the cursor position
autocmd BufReadPost *
  \ if line("'\"") > 1 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif

" Move and delete through the lines
set backspace=indent,eol,start
set whichwrap=b,s,<,>,[,]

" Text width and line wrapping
set nowrap
autocmd FileType text setlocal textwidth=80

" Enable mouse
set mouse=a
set mousehide

" Indentation settings
set shiftwidth=2
set softtabstop=2
set tabstop=2
set smarttab
set expandtab
set shiftround
autocmd FileType python setlocal sw=4 sts=4 et

" Disable bells
set novisualbell
set noerrorbells
set vb t_vb=

" File saving and reading
set autowrite
set autoread
set nobackup
set nowritebackup
set noswapfile

" Open new windows right and below
set splitbelow
set splitright

" Always show the status line
set laststatus=2

" Make commands and undo history bigger
set history=1000
set undolevels=1000

" File and path autocompletion
set path+=**
set wildignore=*.o,*.pyc,*.class,*.d,*/.git/*,*/node_modules/*,.DS_Store
set wildmenu

" Custom filetypes
autocmd BufRead,BufNewFile *.gyp  set filetype=python et ts=2 sw=2
autocmd BufRead,BufNewFile *.gypi set filetype=python et ts=2 sw=2
autocmd BufRead,BufNewFile DEPS   set filetype=python et ts=2 sw=2

" Enable spell cheking for certain types of files
autocmd FileType gitcommit setlocal spell
autocmd FileType text      setlocal spell
autocmd FileType plaintex  setlocal spell
autocmd FileType tex       setlocal spell

" Enable alternative keyboard layout (C-^ to switch)
set keymap=russian-jcukenmac
set iminsert=0
set imsearch=0

" GVim and MacVim settings
if has('gui_running')
  set guioptions-=r
  set guioptions-=L
  set guioptions-=e
  set guifont=Source\ Code\ Pro:h12
endif

" delimitMate settings
let delimitMate_expand_space = 1
let delimitMate_expand_cr = 1

" Gundo settings
let g:gundo_right = 1
let g:gundo_close_on_revert = 1

" YouCompleteMe settings
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/ycm_extra_conf.py'
let g:ycm_python_binary_path = '/usr/local/bin/python3'
let g:ycm_extra_conf_globlist = ['~/projects/*']

" Markdown settings
let g:vim_markdown_folding_disabled = 1

" Syntastic settings
let g:syntastic_javascript_checkers = ['eslint']

" JavaScript settings
let g:javascript_plugin_flow = 1
let g:jsx_ext_required = 1

" ack.vim settings
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" vim-airline settings
let g:airline_theme = 'base16_solarized'

" ------------------------------------------------------------------------------
"  KEYBINDINGS
" ------------------------------------------------------------------------------

" Setup a convenient leader key
let mapleader = ','

" Clear search highlighting
nmap <leader>/ :nohlsearch<CR>

" Git keybindings
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gc :Gcommit<CR>
nnoremap <leader>gp :Gpush<CR>
nnoremap <leader>gl :Gitv<CR>

" Run tests
nnoremap <leader>nt :VimuxRunCommand('npm test')<CR>

" Fix style
nnoremap <leader>jsf :!eslint --fix %<CR>

" Run the file
nnoremap <leader>nj :VimuxRunCommand('node ' . bufname('%'))<CR>
nnoremap <leader>p3 :VimuxRunCommand('python3.6 ' . bufname('%'))<CR>
nnoremap <leader>pr :VimuxRunCommand('python ' . bufname('%'))<CR>
nnoremap <leader>lx :VimuxRunCommand('lualatex -pdf ' . bufname('%'))<CR>

" Show the undo tree
nnoremap <leader>u :GundoToggle<CR>

" Simple navigation and refactoring provided by YouCompleteMe
nnoremap <leader>jd :YcmCompleter GoToDefinitionElseDeclaration<CR>
nnoremap <leader>rr :YcmCompleter RefactorRename
nnoremap <leader>gt :YcmCompleter GetType<CR>
nnoremap <leader>gd :YcmCompleter GetDoc<CR>

" Easier keyboard mappings for keyboard layout switching
inoremap <M-Space> <C-^>
nnoremap <M-Space> a<C-^><Esc>

" Some plugins setup their own keybindings, refer to their manuals to learn
" these keys.  E.g., C-{h,j,k,l} are used to seamlessly switch between Vim
" windows and tmux panes.
